### PR TITLE
Add OpenNIC domains to extended TLDs.

### PR DESCRIPTION
**Pull request by matyapiro31**
OpenNIC domain list is from:
https://en.wikipedia.org/wiki/OpenNIC
OpenNIC domains are non-ICANN TLDs and large free DNS project.

### CODE REVIEW

**Comment by matyapiro31** [comment]
@Stebalien  Please check this.

**Review by lidel — APPROVED** [review]
I verified the list and it matches https://wiki.opennic.org/opennic/dot  :+1: 

@matyapiro31 is there a reason to not also add the peered TLDs?
https://wiki.opennic.org/opennic/dot?redirect=1#peered_top-level_domains

**Comment by matyapiro31** [comment]
I trust OpenNIC, but I don't know much of peered TLDs.
If someone want to add them, I don't hate it.

**Comment by lidel** [comment]
@matyapiro31 fair enough. I think we can merge this as-is then.

I miss permissions, so pinging @Stebalien / @Kubuxu

**Comment by lidel** [comment]
@Stebalien ok to make another release to with OpenNIC? I'd like us to land this in go-ipfs 0.6.

**Comment by Stebalien** [comment]
Done.

**Pull request merged**
